### ISSUE TITLE
Fakeblocks not appearing right away

### ISSUE THREAD

**Issue by Maitlans** [Huskehhh/FakeBlock#19] opened 2020-07-17 08:24 UTC
So when you assign a permission for fakeblocks they don't appear right away or at all if you're not doing anything, you have to be moving around and like interacting with things for them to appear. Would it be possible to have them instantly popup similar how they instantly vanish when the permission is taken away? Thank you!

**Comment by SlimeDog** [comment] 2020-07-17 10:45
Spigot 1.16.1
ProtocolLib 4.6.0-SNAPSHOT-b464
2.0.0-SNAPSHOT-b5

Fake wall appears immediately on (set true) permissions change, but does not disappear immediately on (set false) permission change.

**Comment by Huskehhh** [comment] 2020-07-17 11:14
> Spigot 1.16.1
> 
> ProtocolLib 4.6.0-SNAPSHOT-b464
> 
> 2.0.0-SNAPSHOT-b5
> 
> 
> 
> Fake wall appears immediately on (set true) permissions change, but does not disappear immediately on (set false) permission change.

Roger that! I'll look into it more when I get some time to test

**Comment by Huskehhh** [comment] 2020-07-19 03:21
Should be fixed now. Also fixed a small bug related to the setting of ``fakeblock.admin``. Thanks guys :)

**Comment by SlimeDog** [comment] 2020-07-20 05:21
Spigot 1.16.1
ProtocolLib 4.6.0-SNAPSHOT-b464
FakeBlocks 2.0.0-b6

Still the case: Fake wall appears immediately on (set true) permissions change, but does not disappear immediately on (set false) permission change. Player has to change location (outside current chunk) or disconnect/reconnect.

**Comment by Huskehhh** [comment] 2020-07-20 05:41
> Spigot 1.16.1
> ProtocolLib 4.6.0-SNAPSHOT-b464
> FakeBlocks 2.0.0-b6
> 
> Still the case: Fake wall appears immediately on (set true) permissions change, but does not disappear immediately on (set false) permission change. Player has to change location (outside current chunk) or disconnect/reconnect.

I am unable to replicate. Can you provide the following information

- LuckPerms version
- ProtocolLib version
- Any errors in console?
- Spigot/Paper version
- Latency

**Comment by SlimeDog** [comment] 2020-07-20 07:09
Spigot 1.16.1
ProtocolLib 4.6.0-SNAPSHOT-b464
LuckPerms 5.1.79
FakeBlocks 2.0.0-b6
latency: 25ms

I am able to fail in both directions occasionally. Player has to change location (outside current chunk) or disconnect/reconnect to see changes.

There are no in-game errors or messages. Occasionally, but not explicitly related to permissions changes, console/log reports (amount of delay varies between 100 and 190 ticks):
> [23:56:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8985ms or 179 ticks behind

I am investigating the cause, but `spark` is returning `NoSuchMethodError` presently; waiting for update.

**Comment by Maitlans** [comment] 2020-07-20 07:15
I've tested tonight and it's working properly for me, it instantly changes back and forth if I remove permission or give,

**Comment by Huskehhh** [comment] 2020-07-20 07:45
> Spigot 1.16.1
> ProtocolLib 4.6.0-SNAPSHOT-b464
> LuckPerms 5.1.79
> FakeBlocks 2.0.0-b6
> latency: 25ms
> 
> I am able to fail in both directions occasionally. Player has to change location (outside current chunk) or disconnect/reconnect to see changes.
> 
> There are no in-game errors or messages. Occasionally, but not explicitly related to permissions changes, console/log reports (amount of delay varies between 100 and 190 ticks):
> 
> > [23:56:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8985ms or 179 ticks behind
> 
> I am investigating the cause, but `spark` is returning `NoSuchMethodError` presently; waiting for update.

Am still unable to reproduce. Tried with 50ms ping and worked perfectly fine. Not really sure what's going on here!

Also, if you're not already - I would highly recommend [Paper](https://papermc.io/)!

**Comment by SlimeDog** [comment] 2020-07-20 09:34
It's very early here (02:20), but this is nagging at me, so just a quick note, then back to bed.

Three things happen when I change permissions:
- FakeBlock toggle, which sometimes does not occur
- pHD/HD hologram toggle, which occurs seamlessly in both directions
- ItemJoin menu item changes, which should have no impact until I open the menu, but I am including for completeness

So for these tests, I am watching the hologram and the fake wall toggle (or not, for the wall, sometimes) as I toggle the permission. I will isolate further later this morning, and report. If useful, I can ask my dev -- who wrote the pHD hologram plugin that toggles correctly in both directions -- to have a look and compare the toggle methods.

I cannot change to Paper. Despite their claims, all of my plugins do not work correctly on Paper.

**Comment by SlimeDog** [comment] 2020-07-20 17:54
Updated FakeBlock 2.0.0-b7

For this test, I changed the permission for the pHD hologram trigger to fakeblock.lobby_city (same as the FakeBlock wall), so that I would watch both events toggle (or not) based on the same trigger. Result when I change the LuckPerms group:
- the pHD hologram triggers immediately in both directions.
- the FakeBlock wall does not toggle in the off direction, until the player leaves the proximity and returns.

This behavior is repeatable.

When I change the fakeblock.lobby_city permission for the player, explicitly (not by the LuckPerms group), the FakeBlock wall toggles correctly in both directions. (So does the pHD hologram.)

So perhaps there is a timing issue between the LuckPerms group change and the FakeBlock trigger. Please advise if more information is needed for isolation.

**Comment by SlimeDog** [comment] 2020-07-20 20:35
I would be happy to run a debug version, if that would be helpful to isolate this issue. Or I can invite you to a test server if you want to see this behavior _in situ_.

**Closed** 2020-07-21 00:01 UTC

**Comment by Huskehhh** [comment] 2020-07-21 00:02
> Updated FakeBlock 2.0.0-b7
> 
> For this test, I changed the permission for the pHD hologram trigger to fakeblock.lobby_city (same as the FakeBlock wall), so that I would watch both events toggle (or not) based on the same trigger. Result when I `promote` or `demote` along the LuckPerms track:
> 
>     * the pHD hologram triggers immediately in both directions.
> 
>     * the FakeBlock wall does not toggle in the off direction, until the player leaves the proximity and returns.
> 
> 
> This behavior is repeatable.
> 
> When I directly change the fakeblock.lobby_city permission for the player (not by promoting/demoting along the LuckPerms track), the FakeBlock wall toggles correctly in both directions. (So does the pHD hologram.)
> 
> So perhaps there is a timing issue between the LuckPerms track change and the FakeBlock trigger. Please advise if more information is needed for isolation.

Thanks for this information. It appeared that I wasn't checking for group updates correctly, this should now be fixed in build 8! (along with a little performance fix too!)

**Comment by SlimeDog** [comment] 2020-07-21 00:36
Perfect! And very performant.

Confirmed fixed in b8. Thanks.
